// Generated by Selenium IDE
package ru.stqa.pft.addressbook;


import org.junit.Test;

public class GroupCreationTests extends TestBase {
  @Test
  public void testGroupCreation() {
    startTest();
    login("admin", "secret");
    gotoGroupPage();
    initGroupCreation("new");
    fillGroupForm(new GroupData("test1", "test2", "test3"));
    submitGroupCreation("submit");
    returnToGroupPage();
  }

}
