// Generated by Selenium IDE
package ru.stqa.pft.addressbook;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
public class GroupCreationTests {
  private WebDriver wd;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    wd = new FirefoxDriver();
    js = (JavascriptExecutor) wd;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    wd.quit();
  }
  @Test
  public void testGroupCreation() {
    wd.get("http://localhost/addressbook/");
    wd.manage().window().setSize(new Dimension(896, 868));
    wd.findElement(By.name("user")).sendKeys("admin");
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys("secret");
    wd.findElement(By.cssSelector("input:nth-child(7)")).click();
    wd.findElement(By.linkText("groups")).click();
    wd.findElement(By.name("new")).click();
    wd.findElement(By.name("group_name")).click();
    wd.findElement(By.name("group_name")).sendKeys("test1");
    wd.findElement(By.name("group_header")).click();
    wd.findElement(By.name("group_header")).sendKeys("test2");
    wd.findElement(By.name("group_footer")).click();
    wd.findElement(By.name("group_footer")).sendKeys("test3");
    wd.findElement(By.name("submit")).click();
    wd.findElement(By.linkText("group page")).click();
    wd.findElement(By.linkText("Logout")).click();
  }
}
