// Generated by Selenium IDE
package ru.stqa.pft.addressbook;

import org.junit.Test;


public class GroupDeletionTests extends TestBase {

  @Test
  public void groupDeletionTests() {
    startTest();
    login("admin", "secret");
    gotoGroupPage();
    selectGroup();
    deleteSelectedGroups();
    returnToGroupPage();
  }

}
