// Generated by Selenium IDE
package ru.stqa.pft.addressbook;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class ProfileCreationTests {
  private WebDriver wd;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    wd = new FirefoxDriver();
    js = (JavascriptExecutor) wd;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    wd.quit();
  }
  @Test
  public void profileCreationTests() {
    startTest();
    login("admin", "secret");
    goToNewProfile("add new");
    fillProfileCreation(new ProfileData("David", "Test", "22222222", "test@gmail.com"));
    submitProfileCreation("input:nth-child(87)");
    logout("Logout");
  }

  private void logout(String logout) {
    wd.findElement(By.linkText(logout)).click();
  }

  private void submitProfileCreation(String s) {
    wd.findElement(By.cssSelector(s)).click();
  }

  private void fillProfileCreation(ProfileData profileData) {
    wd.findElement(By.name("firstname")).sendKeys(profileData.getFirstname());
    wd.findElement(By.name("lastname")).sendKeys(profileData.getLastname());
    wd.findElement(By.name("home")).sendKeys(profileData.getHomephone());
    wd.findElement(By.name("email")).sendKeys(profileData.getEmail());
  }

  private void goToNewProfile(String s) {
    wd.findElement(By.linkText(s)).click();
  }

  private void login(String username, String password) {
    wd.findElement(By.name("user")).sendKeys(username);
    wd.findElement(By.name("pass")).click();
    wd.findElement(By.name("pass")).sendKeys(password);
    wd.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  private void startTest() {
    wd.get("http://localhost/addressbook/");
    wd.manage().window().setSize(new Dimension(896, 868));
  }
}
