// Generated by Selenium IDE
package ru.stqa.pft.addressbook.tests;

import org.junit.Test;


public class GroupDeletionTests extends TestBase {

  @Test
  public void groupDeletionTests() {

    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnToGroupPage();
  }

}
